### ISSUE TITLE
deepMap and deepFind does not appear to be going deep

### ISSUE THREAD

**Issue by McPo** [fernandopasik/react-children-utilities#1]
It appears deepMap and deepFind, doesn't go deep, however deepForEach does.
```
Children.deepMap(children, child => { console.log('deepFind type', child.type); return child; });

Children.deepFind(children, child => { console.log('deepFind type', child.type); return false; });
```

**Comment by McPo** [comment]
On further investigation, I had no issue with deepMap (I was initially trying to do deepMap on already precompiled react code, so perhaps this influenced the results).

However it appears that deepFind does go deep, but it misses out several node.

**Comment by fernandopasik** [comment]
Thanks @McPo for taking the time to add this issue. Do you have an example where deepFind is missing nodes?

**Comment by fernandopasik** [comment]
@McPo I've revised deepFind and I couldn't find an example which avoids nodes.
Just for you to know it doesn't traverse by tree level, it goes as deep possible on each node so let's say we have

```jsx
const DeepFound = props => (<div>{ Children.deepFind(props.children, child => child.type === 'i') }</div>);
```

and we want to test it on this:
```jsx
<DeepFound>
  <b>1</b>
  <b><span><i>2</i></span></b>
  <span><i>3</i></span>
  <i>4</i>
</DeepFound>);
```

In this case the nodes visited would be `b -> b -> span -> i` and it would end there on the i with text 2, the rest of the nodes would have never been visited.
