### ISSUE TITLE
deepFind should return the element found, not its root

### ISSUE THREAD

**Issue by riywo** [fernandopasik/react-children-utilities#12]
**Is your feature request related to a problem? Please describe.**
I'd like to get an element which has specific props from children by `deepFind`. I assumed it returns the element which is matched agains the test function, but actually it returns its root i.e.

Expected:
```
          <i>3</i>
```

Actual:
```
        <span>
          <i>3</i>
        </span>
```

**Describe the solution you'd like**
Change `deepFind` behaviour to return the found element instead of its root element. (Or introduce a new function like `deepElementFind`)

**Describe alternatives you've considered**
I could use `deepForEach` but it visits all elements unnecessarily.

**Additional context**
I found #1 but I'm not sure the current behaviour is expected. If not, it is a bug.

**Comment by fernandopasik** [comment]
Thanks for your contribution!
