### ISSUE TITLE
deepMap, deepFind and deepForEach do not use index & children arguments

### ISSUE THREAD

**Issue by dpinol** [fernandopasik/react-children-utilities#16]
The deepMap & deepFind specify index & children arguments for the function that need to be passed. However, this arguments are not specified when calling the functions. In deepForEach the same happens for the index argument.

## Expected behavior

The callback functions should be called with (currentNode, index, children)

## Current behavior

The callback functions are called with (currentNode)

## Possible solution

https://github.com/fernandopasik/react-children-utilities/pull/17

**Comment by fernandopasik** [comment]
This is a major finding, thanks @dpinol for opening a PR

**Comment by fernandopasik** [comment]
I think the same is happening for `filter` and `deepFilter` could you fix those as well?

**Comment by fernandopasik** [comment]
fixed by #17

**Comment by fernandopasik** [comment]
Thanks @dpinol, I've added you to the contributors list

**Comment by dpinol** [comment]
@fernandopasik my pleasure!
