### ISSUE TITLE
onlyText: reduce calls of validate fn

### ISSUE THREAD

**Issue by inomdzhon** [fernandopasik/react-children-utilities#160]
# Report

We did call `React.isValidElement()` more than one:

1. In first condition – two times. Because `hasChildren()` call `React.isValidElement()` too.
2. In second condition – four times. Because we recall `React.isValidElement()` in the place and than in `hasChildren()`.

## Possible solution

We can call `React.isValidElement()` once, save the result to variable and than reuse them. And we shouldn't use `hasChildren()`.

**Comment by fernandopasik** [comment]
Thank you for raising this issue and PR!

**Comment by fernandopasik** [comment]
Just to understand the purpose of this issue. Is it just code optimisation? I don't think there's a bug here

**Comment by inomdzhon** [comment]
> Just to understand the purpose of this issue. Is it just code optimisation? I don't think there's a bug here

Sure, it's just code optimisation. It's not the bug, sorry... It's like a feature.

**Comment by fernandopasik** [comment]
Thank you @inomdzhon for contributing and proposing that optimisations are needed, I've taken parts of the contribution and merged changes.
