### ISSUE TITLE
Deepmap nested children

### ISSUE THREAD

**Issue by 99uno** [fernandopasik/react-children-utilities#23]
If I have a custom component as a child, when I use deepMap, its children are not being iterated. Eg:

```
<MyComponent>
    <User/>
</MyComponent>
```
Where user contains two input fields. When I use deepMap(children) inside MyComponent user inputs are not included. Is it possible to deepMap while there is a component inside?

**Comment by fernandopasik** [comment]
It's a limitation of this library, it only iterates through the children of the component you are implementing. If you wanted to do this in `MyComponent` as well as in `User` children, you'll need to implement in both the mapping.
