### ISSUE TITLE
groupByType support UppercaseComponent, not only lowercase like div + span

### ISSUE THREAD

**Issue by TSMMark** [fernandopasik/react-children-utilities#27]
# Feature Request

## Problem to solve

Be able to use groupByType on custom components. Currently only works on native/lowercase react elements/nodes like div, span, p, li, etc.

Consider 

```js
<MyComponent>
  <MyTab />
  <MyTab />
  <MyButton />
  <p />
  <p />
</MyComponent>
```

`groupByType(children)` inside MyComponent could return:

```js
{
  MyTab: [<MyTab />, <MyTab />],
  MyButton: [<MyButton />],
  p: [<p />, <p />],
}
```

## Possible implementation

Currently you can easily use lodash.groupBy and React.Children.toArray to accomplish this:

```js
groupBy(Children.toArray(children), (child) => child.type.name)
```

## Footnote

Any caveats or reasons this wouldn't work or shouldn't be implemented? I could probably try implementing and submit PR if it would be accepted

**Comment by fernandopasik** [comment]
Thank you for raising this feature request!

Your proposal made me add one new utility function for getting the element name
https://fernandopasik.com/react-children-utilities/get-element-name
and also what you've requested, that you can pass different types in the `types` array.

Now you can pass:

- Tag name string
- React Element name string
- React Element function
- React Element class

I've also update documentation: 
https://fernandopasik.com/react-children-utilities/group-by-type

Please let me know if this works as you requested.

**Comment by TSMMark** [comment]
Amazing! We actually ran into a gotcha with this approach in React production mode, when we tried my original proposal of:

```
groupBy(Children.toArray(children), (child) => child.type.name)
```

I'm sure you are aware but `child.type.name` seems to become minified in production transpile.

---

I will try to test your version soon. Thank you!

**Comment by TSMMark** [comment]
I think it's pretty common for production bundles with standard babel plugins.. Related examples I just found: 

 - https://stackoverflow.com/q/61750233/2696867
 - https://www.albertgao.xyz/2017/10/31/why-this-react-code-not-work-in-production/

What we ended up resorting to is essentially manually grouping expected children by actual component class/function by object reference. E.g. `child.type === SomeReactComponentFunction` 

Example snippet: 

```js
const groupedChildren = useMemo(() => {
  const groupedChildren = {
    ExtraRow: [],
    RowBanner: [],
    RowCell: [],
    SharedComponents: [],
  }

  Children.forEach(children, (child) => {
    switch (child.type) {
    case ExtraRow:
      groupedChildren.ExtraRow.push(child)
      break
    case RowCell:
      groupedChildren.RowCell.push(child)
      break
    case RowBanner:
      groupedChildren.RowBanner.push(child)
      break
    case SharedComponents:
      groupedChildren.SharedComponents.push(child)
      break
    default:
      break
    }
  })

  return groupedChildren
}, [children])
```

I think my OP request to rely on component names is not suitable for production unfortunately. Sorry about that.

It might be possible to generalize the above code snippet into a custom hook that will work with any components, and reduce some of the boilerplate in manually doing a big switch case...

Imagining it would have an interface similar to this (flow types included):

```js
const groupedChildren = useGroupedChildren(children, {
  // This object is the `Name: ReactComponent` map
  RowBanner: RowBanner,
  RowCell: RowCell,
  SharedComponents: SharedComponents,
})

// groupedChildren would include the properties provided above, for example:
groupedChildren.RowBanner.length // => 1
groupedChildren.RowCell.length // => 5
groupedChildren.SharedComponents.length // => 0
// etc
```

Example usage including flow types, where `useGroupedChildren` is typed as a generic:

```js
const groupedChildren = useGroupedChildren<{|
  RowBanner: React$Element<typeof RowBanner>,
  RowCell: React$Element<typeof RowCell>,
  SharedComponents: React$Element<typeof SharedComponents>,
|}>(children, {
  RowBanner: RowBanner,
  RowCell: RowCell,
  SharedComponents: SharedComponents,
})
```

**Comment by fernandopasik** [comment]
My implementation also works when you pass the `function or class` in the `types` array. Them problem is to construct the groups object I'm still relaying on the `name` attribute in those cases and I guess that could break.

One doubt I have though is that Function.name is actually a native property and I don't think it gets minified.

```
console.log((function MyName() {}).name)
```

**Comment by fernandopasik** [comment]
`MyName` gets minified in that case but if you pass MyName instead of `MyName` in the types array that should still work after minification

Perhaps I should remove the possibility of passing the class or function name as string.

**Comment by TSMMark** [comment]
I think uglify / terser will shorten function names but I haven't confirmed yet. e.g. https://webpack.js.org/plugins/terser-webpack-plugin

**Comment by fernandopasik** [comment]
Since you can pass a React Element function or a  React Element class, that avoids the problem of the minification. If you find further problems I'll reopen this issue.
