### ISSUE TITLE
Problem with husky on npm 7.20.*

### ISSUE THREAD

**Issue by JulioOrellana** [fernandopasik/react-children-utilities#28]
# Bug Report

Hello, I am having a problem using `npm v7.20.3` with `react-children-utilities v2.5.4`. As I show in the next image, `npm install` can't finish because there is a problem with husky library. This error only happens with npm 7.20.*, if I downgrade to npm 6.*.* my install finish correctly. I have tried installing husky manually, globally, but it is still failing.

I am looking for a way to solve this in order to update to npm 7.20.*

<img width="921" alt="Screen Shot 2021-07-30 at 10 00 44" src="https://user-images.githubusercontent.com/10372340/127678727-aa46da8a-c207-48b1-aa99-7547a5af5b9c.png">

## Steps to reproduce

1. Update npm to v7.20.3
2. Install this library in your project
3. Maybe delete `node_modules` and `npm install` again

Any help would be highly appreciated :D, sorry if I am missing something.

**Comment by fernandopasik** [comment]
Thank you for raising this issue!
I'm investigating if it's related to https://github.com/typicode/husky/issues/1003

**Comment by fernandopasik** [comment]
Please try again with the new version I've just published https://github.com/fernandopasik/react-children-utilities/releases/tag/v2.6.0
