### ISSUE TITLE
How to get deep children

### ISSUE THREAD

**Issue by einarq** [fernandopasik/react-children-utilities#3]
Is this meant to be used when testing? Can't otherwise see how to get children recursively, at least children is not deep in my experiments.

**Comment by fernandopasik** [comment]
You could use it for testing, but seems more logical that in tests you will compare two snapshots of a component

**Comment by einarq** [comment]
Do you have an example of using for instance deepMap during normal
rendering? (not in a test)

**Comment by fernandopasik** [comment]
Sure

if you have the following element:

```
const List = () => (
  <ul>
    <li>First</li>
    <li>Second</li>
    <li>Third</li>
  </ul>
);
```

And you have another element like:
```
const TitlesList = (props) => {
  const children = Children.deepMap(props.children,
          child => (
            child.type === 'li'
              ? cloneElement(child, { ...child.props, className: 'title' })
              : child
          ),
        );
  return (
    <div className="titles-list">
        {children}
    </div>
  );
};
```

And they are used like:

```
<TitlesList>
   <List/>
</TitlesList>
```

**Comment by fernandopasik** [comment]
What are you trying to accomplish that you need from the library?

**Comment by fernandopasik** [comment]
I think the library already supports what you are looking for. If further is needed I'll reopen this issue.
