### ISSUE TITLE
deepFilter doesn't match to grandchildren

### ISSUE THREAD

**Issue by lufia** [fernandopasik/react-children-utilities#30]
# Bug Report

*deepFilter* doesn't match to grandchildren. Is this expected?

## Expected behavior

```html
<div>
  <span>1</span>
  <span>2</span>
  <span>3</span>
</div>
```

## Current behavior

```html
<div>
  <span>1</span>
  <span>2</span>
</div>
```

## Steps to reproduce

Run this.

```tsx
import React from "react";
import { render } from "react-dom";
import { deepFilter } from "react-children-utilities";

type DeepFilteredProps = Readonly<{
	children: React.ReactNode;
}>;

const DeepFiltered: React.VFC<DeepFilteredProps> = ({ children }) => {
	return <div>{deepFilter(children, item => item && (item as React.ReactElement).type === "span")}</div>;
}

const Example: React.VFC = () => {
	return (
		<DeepFiltered>
			<span>1</span>
			<span>2</span>
			<div>
				<span>3</span>
			</div>
		</DeepFiltered>
	);
}

render(<Example />, document.body);
```

## Possible solution

If this is expected, I think the example of *deepFilter* should be updated.

**Comment by fernandopasik** [comment]
The behaviour is the expected, because `div` is analyzed first and filtered out since is not a `span`. It doesn't matter what is grandchildren, if the child is already filtered out.

I think the example in the website illustrates this https://fernandopasik.com/react-children-utilities/deep-filter

**Comment by lufia** [comment]
I see. Thank you.

**Comment by fabpico** [comment]
@fernandopasik I was also confused about this behavior. With **deep**, I expected a traversal through all children first. Currently I would more call it shallow-deep 😄. So currently if I want to find deep children, all parents must also match the filter criteria, which does not apply for my use case. My use case is to get required form elements from a complex nested form.  
I could use `deepForEach` and add matches into a new array, but I liked the idea to use `deepFilter`.

May be reopen or make an option for it? Or make the stopping for going deeper as option, and deep traverse by default?
