### ISSUE TITLE
Any opportunity for a deepFilter?

### ISSUE THREAD

**Issue by dptoot** [fernandopasik/react-children-utilities#4]
I would like to iterate over all children of an element and then filter it down to  components of a particular type.  Any opportunity to extend the library?

**Comment by fernandopasik** [comment]
Sure, could you share here an example what do you want to accomplish?

**Comment by dptoot** [comment]
Sure!

Let's say I wanted to search deep children and only return a specific type?

```js const controlledComponents = Children.deepFilter(props.children, (child) => child.type.name.includes('Controlled'))```

In theory this would provide the user with an array of only components that satisfied the assertion and had the word Controlled in their name?

**Comment by fernandopasik** [comment]
This should work already with the deepFilter method

**Comment by dptoot** [comment]
thanks!
