### ISSUE TITLE
Support named imports by exporting named constants

### ISSUE THREAD

**Issue by TSMMark** [fernandopasik/react-children-utilities#8]
Currently you have to import this way:

```js
import Children from 'react-children-utilities'
```

It would be great if we could import named exports like:

```js
import { onlyText } from 'react-children-utilities'
```

It should be easy for this module to use es6 named exports, something like this:

```js
/**
 * Filter children
 * @param   {object} children - React component children
 * @param {function} filterFn - Array filter callback
 * @returns  {array}          - Filtered children
 */
export function filter(children: number, filterFn: (child: Node) => boolean): Node {
  return Children
    .toArray(children)
    .filter(filterFn);
};

export default {

  ...Children,

  filter,
  etc,
  etc,
  etc,
  onlyText,

};
```

**Comment by TSMMark** [comment]
I have no problem implementing this, would you accept a PR?

**Comment by fernandopasik** [comment]
Thanks for your contribution @TSMMark! I was planning to do this and to spread in different files each of them.

**Comment by TSMMark** [comment]
Direct file imports would work too! Anything to shave a few bytes from the end bundle 😄 

I was happy to contribute to this awesome little library, thanks for publishing it! `onlyText` was the perfect fit for our case. Much appreciation
